syntax = "proto3";

package com.goodskill.monomorph.dto.generated.proto.orderdto;

option java_multiple_files = true;
option java_package = "com.goodskill.monomorph.dto.generated.proto.orderdto";

import "google/protobuf/timestamp.proto";

message OrderDTODTO {
  int64 serialVersionUID = 1;
  int64 seckillId = 2;
  string userPhone = 3;
  int32 status = 4;
  google.protobuf.Timestamp createTime = 5;
  string serverIp = 6;
  string userIp = 7;
  string userId = 8;
  string goodsName = 9;
  string goodsTitle = 10;
  string goodsImg = 11;
  double seckillPrice = 12;
  string stateDesc = 13;
  string alipayTradeNo = 14;
  google.protobuf.Timestamp payCompleteTime = 15;
}
