syntax = "proto3";

package com.youlai.mall.monomorph.dto.generated.proto.userauthinfo;

option java_multiple_files = true;
option java_package = "com.youlai.mall.monomorph.dto.generated.proto.userauthinfo";

message UserAuthInfoDTO {
  int64 userId = 1;
  string username = 2;
  string password = 3;
  int32 status = 4;
  repeated string roles = 5;
  repeated string perms = 6;
  int64 deptId = 7;
  int32 dataScope = 8;
  string nickname = 9;
  string mobile = 10;
  string email = 11;
  string avatar = 12;
}
