syntax = "proto3";

package com.goodskill.monomorph.id.generated.proto.seckillservice;

option java_multiple_files = true;
option java_package = "com.goodskill.monomorph.id.generated.proto.seckillservice";

import "shared.proto";
import "seckill_mock_request_dto.proto";

service SeckillServiceService {
  rpc createObject(CreateObjectRequest) returns (com.goodskill.monomorph.id.shared.RefactoredObjectID);
  rpc endSeckill(EndSeckillRequest) returns (EndSeckillResponse);
  rpc execute(ExecuteRequest) returns (ExecuteResponse);
  rpc getSuccessKillCount(GetSuccessKillCountRequest) returns (GetSuccessKillCountResponse);
  rpc prepareSeckill(PrepareSeckillRequest) returns (PrepareSeckillResponse);
}

message CreateObjectRequest {
  string clientID = 1;
  ConstructorArgs constructorArgs = 2;
}

message ConstructorArgs {
  // SeckillService is an interface; no constructor arguments.
}

message EndSeckillRequest {
  com.goodskill.monomorph.id.shared.RefactoredObjectID objectId = 1;
  int64 seckillId = 2;
}

message EndSeckillResponse {
  bool success = 1;
}

message ExecuteRequest {
  com.goodskill.monomorph.id.shared.RefactoredObjectID objectId = 1;
  com.goodskill.monomorph.dto.generated.proto.seckillmockrequestdto.SeckillMockRequestDTODTO requestDto = 2;
  int32 strategyNumber = 3;
}

message ExecuteResponse {
}

message GetSuccessKillCountRequest {
  com.goodskill.monomorph.id.shared.RefactoredObjectID objectId = 1;
  int64 seckillId = 2;
}

message GetSuccessKillCountResponse {
  int64 count = 1;
}

message PrepareSeckillRequest {
  com.goodskill.monomorph.id.shared.RefactoredObjectID objectId = 1;
  int64 seckillId = 2;
  int32 seckillCount = 3;
  string taskId = 4;
}

message PrepareSeckillResponse {
}