syntax = "proto3";

package ltd.newbee.mall.monomorph.id.generated.proto.newbeemallusertokenmapper;

option java_multiple_files = true;
option java_package = "ltd.newbee.mall.monomorph.id.generated.proto.newbeemallusertokenmapper";

import "shared.proto";
import "mall_user_token.proto";

service NewBeeMallUserTokenMapperService {
    rpc createObject(CreateObjectRequest) returns (ltd.newbee.mall.monomorph.id.shared.RefactoredObjectID);
    rpc selectByToken(SelectByTokenRequest) returns (SelectByTokenResponse);
}

message CreateObjectRequest {
    string clientID = 1;
    ConstructorArgs constructorArgs = 2;
}

message ConstructorArgs {
    // Intentionally empty: NewBeeMallUserTokenMapper is an interface and has no constructor arguments.
}

message SelectByTokenRequest {
    ltd.newbee.mall.monomorph.id.shared.RefactoredObjectID refactoredObjectID = 1;
    string token = 2;
}

message SelectByTokenResponse {
    ltd.newbee.mall.monomorph.dto.generated.proto.mallusertoken.MallUserTokenDTO result = 1;
}