syntax = "proto3";

package com.youlai.mall.monomorph.id.generated.proto.skuservice;

option java_multiple_files = true;
option java_package = "com.youlai.mall.monomorph.id.generated.proto.skuservice";

import "shared.proto";
import "sku_info_dto.proto";
import "lock_sku_dto.proto";

service SkuServiceService {
  rpc createObject(CreateObjectRequest) returns (com.youlai.mall.monomorph.id.shared.RefactoredObjectID);

  // SkuService specified methods
  rpc getSkuInfo(GetSkuInfoRequest) returns (GetSkuInfoResponse);
  rpc getSkuInfoList(GetSkuInfoListRequest) returns (GetSkuInfoListResponse);
  rpc lockStock(LockStockRequest) returns (LockStockResponse);
  rpc unlockStock(UnlockStockRequest) returns (UnlockStockResponse);
  rpc deductStock(DeductStockRequest) returns (DeductStockResponse);
}

message CreateObjectRequest {
  string clientID = 1;
  ConstructorArgs constructorArgs = 2;
}

message ConstructorArgs {
  // SkuService is an interface and has no constructor parameters.
}

message GetSkuInfoRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  int64 sku_id = 2;
}

message GetSkuInfoResponse {
  com.youlai.mall.monomorph.dto.generated.proto.skuinfodto.SkuInfoDTODTO sku_info = 1;
}

message GetSkuInfoListRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  repeated int64 sku_ids = 2;
}

message GetSkuInfoListResponse {
  repeated com.youlai.mall.monomorph.dto.generated.proto.skuinfodto.SkuInfoDTODTO sku_infos = 1;
}

message LockStockRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  string order_token = 2;
  repeated com.youlai.mall.monomorph.dto.generated.proto.lockskudto.LockSkuDTODTO lock_sku_list = 3;
}

message LockStockResponse {
  bool success = 1;
}

message UnlockStockRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  string order_sn = 2;
}

message UnlockStockResponse {
  bool success = 1;
}

message DeductStockRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  string order_sn = 2;
}

message DeductStockResponse {
  bool success = 1;
}