syntax = "proto3";

package com.youlai.mall.monomorph.id.generated.proto.sysuserservice;

option java_multiple_files = true;
option java_package = "com.youlai.mall.monomorph.id.generated.proto.sysuserservice";

import "shared.proto";
import "user_auth_info.proto";

service SysUserServiceService {
  rpc createObject(CreateObjectRequest) returns (.com.youlai.mall.monomorph.id.shared.RefactoredObjectID);
  rpc getUserAuthInfo(GetUserAuthInfoRequest) returns (GetUserAuthInfoResponse);
}

message CreateObjectRequest {
  string clientID = 1;
  ConstructorArgs constructorArgs = 2;
}

message ConstructorArgs {
  // No constructor parameters for SysUserService interface.
}

message GetUserAuthInfoRequest {
  .com.youlai.mall.monomorph.id.shared.RefactoredObjectID object_id = 1;
  string username = 2;
}

message GetUserAuthInfoResponse {
  .com.youlai.mall.monomorph.dto.generated.proto.userauthinfo.UserAuthInfoDTO user_auth_info = 1;
}