syntax = "proto3";

package com.youlai.mall.monomorph.dto.generated.proto.memberregisterdto;

option java_multiple_files = true;
option java_package = "com.youlai.mall.monomorph.dto.generated.proto.memberregisterdto";

message MemberRegisterDtoDTO {
  int32 gender = 1;
  string nickName = 2;
  string mobile = 3;

  // java.time.LocalDate represented as ISO-8601 date string.
  string birthday = 4;

  string avatarUrl = 5;
  string openid = 6;
  string sessionKey = 7;
  string city = 8;
  string country = 9;
  string language = 10;
  string province = 11;
}
