syntax = "proto3";

package com.youlai.mall.monomorph.id.generated.proto.umsmemberservice;

option java_multiple_files = true;
option java_package = "com.youlai.mall.monomorph.id.generated.proto.umsmemberservice";

import "shared.proto";
import "product_history_vo.proto";
import "member_register_dto.proto";
import "member_auth_dto.proto";
import "member_address_dto.proto";

service UmsMemberServiceService {
  rpc createObject(CreateObjectRequest) returns (com.youlai.mall.monomorph.id.shared.RefactoredObjectID);

  rpc addProductViewHistory(AddProductViewHistoryRequest) returns (AddProductViewHistoryResponse);
  rpc deductBalance(DeductBalanceRequest) returns (DeductBalanceResponse);
  rpc getMemberOpenId(GetMemberOpenIdRequest) returns (GetMemberOpenIdResponse);
  rpc listMemberAddresses(ListMemberAddressesRequest) returns (ListMemberAddressesResponse);
  rpc loadUserByMobile(LoadUserByMobileRequest) returns (LoadUserByMobileResponse);
  rpc loadUserByOpenId(LoadUserByOpenIdRequest) returns (LoadUserByOpenIdResponse);
  rpc registerMember(RegisterMemberRequest) returns (RegisterMemberResponse);
}

message CreateObjectRequest {
  string clientID = 1;
  ConstructorArgs constructorArgs = 2;
}

message ConstructorArgs {
  // No constructor parameters for an interface.
}

message AddProductViewHistoryRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  com.youlai.mall.monomorph.dto.generated.proto.producthistoryvo.ProductHistoryVODTO product_history_vo = 2;
}

message AddProductViewHistoryResponse {}

message DeductBalanceRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  int64 member_id = 2;
  int64 amount = 3;
}

message DeductBalanceResponse {}

message GetMemberOpenIdRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  int64 member_id = 2;
}

message GetMemberOpenIdResponse {
  string open_id = 1;
}

message ListMemberAddressesRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  int64 member_id = 2;
}

message ListMemberAddressesResponse {
  repeated com.youlai.mall.monomorph.dto.generated.proto.memberaddressdto.MemberAddressDTODTO addresses = 1;
}

message LoadUserByMobileRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  string mobile = 2;
}

message LoadUserByMobileResponse {
  com.youlai.mall.monomorph.dto.generated.proto.memberauthdto.MemberAuthDTODTO member_auth = 1;
}

message LoadUserByOpenIdRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  string openid = 2;
}

message LoadUserByOpenIdResponse {
  com.youlai.mall.monomorph.dto.generated.proto.memberauthdto.MemberAuthDTODTO member_auth = 1;
}

message RegisterMemberRequest {
  com.youlai.mall.monomorph.id.shared.RefactoredObjectID refactored_object_id = 1;
  com.youlai.mall.monomorph.dto.generated.proto.memberregisterdto.MemberRegisterDtoDTO member_register_dto = 2;
}

message RegisterMemberResponse {
  int64 member_id = 1;
}