syntax = "proto3";

package com.lakesidemutual.monomorph.id.shared.leasing;

option java_multiple_files = true;
option java_package = "com.lakesidemutual.monomorph.id.shared.leasing";

import "shared.proto";

service LeasingService {
    rpc acquireLease(LeaseRequest) returns (LeaseResponse);
    rpc renewLease(LeaseRequest) returns (LeaseResponse);
    rpc releaseLease(LeaseRequest) returns (LeaseResponse);
}

message LeaseRequest {
    com.lakesidemutual.monomorph.id.shared.RefactoredObjectID instanceID = 1;
    string clientID = 2;
}

message LeaseResponse {
    bool success = 1;
}